<?php

namespace MiwSpotifyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtiquetasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtiquetasRepository extends EntityRepository
{
}
